import calorie_counter, protein_counter, carb_counter
def show_numbers(date):
    call_calorie = calorie_counter.calorie_counter(date)
    call_protein = protein_counter.protein_counter(date)
    call_carb = carb_counter.carb_counter(date)
    calorie_sum = sum(call_calorie)
    protein_sum = sum(call_protein)
    carb_sum = sum(call_carb)
    print('This is the function that will sum and average totals by week')
    calorie_average = calorie_sum / len(call_calorie)
    protein_average = protein_sum / len(call_protein)
    carb_average = carb_sum / len(call_protein)
    print()
    print(f'Your calorie total for last week is: {calorie_sum}')
    print(f'Your calorie average for last week is {round(calorie_average)}')
    print(f'Your protein total for last week is: {protein_sum}')
    print(f'Your protein average for last week is {round(protein_average)}')
    print(f'Your carb total for last week is: {carb_sum}')
    print(f'Your carb average for last week is {round(carb_average)}')
    return calorie_sum, round(calorie_average), protein_sum, round(protein_average), \
        carb_sum, round(carb_average)